name: rodriigomedeiros/sim2ped-mobile
author:
  name: Rodrigo Medeiros
  email: rodriigomedeiros@gmail.com
  url: null
copyright: 2015 Rodrigo Medeiros
description: 'Sistema Inteligente de Monitoramento da Prevenção do Pé Diabético (SIM2PeD), versão Mobile.'
